# ================================
# WhaleHire 前端项目 Docker Compose
# DevOps 生产环境配置
# ================================

version: '3.8'

services:
  # 前端应用服务
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # 生产环境变量
        VITE_API_BASE_URL: https://hire.chaitin.net/api
        VITE_OAUTH_CALLBACK_URL: https://hire.chaitin.net/oauth/callback
        VITE_APP_TITLE: WhaleHire 智能招聘系统
        VITE_APP_VERSION: 1.0.0
        VITE_APP_ENV: production
        VITE_ENABLE_MOCK: false
        VITE_DEBUG: false
        VITE_ENABLE_DEVTOOLS: false
        VITE_BUILD_SOURCEMAP: false
        VITE_BUILD_MINIFY: true
        # 构建元数据
        BUILD_DATE: ${BUILD_DATE:-}
        GIT_COMMIT: ${GIT_COMMIT:-}
        GIT_BRANCH: ${GIT_BRANCH:-}
        BUILD_NUMBER: ${BUILD_NUMBER:-}
      target: production
    image: wh-frontend:latest
    container_name: wh-frontend-prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      # Nginx 运行时环境变量
      NGINX_WORKER_PROCESSES: auto
      NGINX_WORKER_CONNECTIONS: 1024
      NGINX_KEEPALIVE_TIMEOUT: 65
      NGINX_CLIENT_MAX_BODY_SIZE: 10m
    volumes:
      # SSL 证书挂载（如果需要）
      - ./ssl:/etc/nginx/ssl:ro
      # 自定义 Nginx 配置（可选）
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # 日志目录
      - ./logs:/var/log/nginx
    networks:
      - frontend-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`hire.chaitin.net`)"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  # 开发环境服务（可选）
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:8888/api
        VITE_OAUTH_CALLBACK_URL: http://localhost:5173/oauth/callback
        VITE_APP_ENV: development
        VITE_DEBUG: true
        VITE_ENABLE_DEVTOOLS: true
        VITE_BUILD_SOURCEMAP: true
        VITE_BUILD_MINIFY: false
      target: production
    image: wh-frontend:dev
    container_name: wh-frontend-dev
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      NGINX_WORKER_PROCESSES: 1
    networks:
      - frontend-network
    profiles:
      - dev

  # 测试环境服务（可选）
  frontend-staging:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: https://staging.hire.chaitin.net/api
        VITE_OAUTH_CALLBACK_URL: https://staging.hire.chaitin.net/oauth/callback
        VITE_APP_ENV: staging
        VITE_DEBUG: false
        VITE_ENABLE_DEVTOOLS: false
        VITE_BUILD_SOURCEMAP: true
        VITE_BUILD_MINIFY: true
      target: production
    image: wh-frontend:staging
    container_name: wh-frontend-staging
    restart: unless-stopped
    ports:
      - "8081:80"
    networks:
      - frontend-network
    profiles:
      - staging

networks:
  frontend-network:
    driver: bridge
    name: wh-frontend-network

volumes:
  nginx-logs:
    driver: local
    name: wh-frontend-logs