version: '3.8'

services:
  # PostgreSQL 数据库 - 开发环境
  whalehire-db:
    image: pgvector/pgvector:pg17
    container_name: whalehire-postgres-dev
    environment:
      POSTGRES_DB: whalehire
      POSTGRES_USER: whalehire
      POSTGRES_PASSWORD: whalehire123
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U whalehire -d whalehire"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis 缓存
  whalehire-redis:
    image: redis:7-alpine
    container_name: whalehire-redis
    environment:
      REDIS_PASSWORD: redis123
    command: redis-server --requirepass redis123
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - whalehire-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis123", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local
