[err-permission]
other = "Permission denied"

[err-user-not-found]
other = "User not found"

[err-user-lock]
other = "User is locked"

[err-password]
other = "Incorrect password"

[err-only-admin]
other = "Only admin can perform this operation"

[err-invite-code-invalid]
other = "Invalid invitation code"

[err-email-invalid]
other = "Invalid email format"

[err-oauth-state-invalid]
other = "Invalid OAuth state"

[err-unsupported-platform]
other = "Unsupported platform"

[err-not-invited]
other = "Not invited"

[err-dingtalk-not-enabled]
other = "DingTalk is not enabled"

[err-custom-not-enabled]
other = "OAuth is not enabled"

[err-user-limit]
other = "User limit reached"

[err-miss-key]
other = "file key miss"

[err-department-required]
other = "Department ID is required"

[err-jobprofile-required]
other = " Jobprofile ID is required"

[err-jobskillmeta-required]
other = " JobSkillMeta ID is required"

[err-invalid-param]
other = "Invalid Param: {{.message}}"

[err-jobprofile-has-resumes]
other = "Job profile has associated resumes"

[err-jobprofile-polish-min-length]
other = "Job profile description input validation error: {{.message}}"

[err-screening-task-not-found]
other = "Screening task not found"

[err-screening-task-running]
other = "Cannot delete running task, please wait for completion or failure"

[err-screening-task-delete-failed]
other = "Failed to delete screening task"

[err-notification-setting-create-failed]
other = "Failed to create notification setting"

[err-notification-setting-get-failed]
other = "Failed to get notification setting"

[err-notification-setting-list-failed]
other = "Failed to list notification settings"

[err-notification-setting-update-failed]
other = "Failed to update notification setting"

[err-notification-setting-delete-failed]
other = "Failed to delete notification setting"

[err-notification-setting-not-found]
other = "Notification setting not found"

[err-resume-mailbox-setting-not-found]
other = "Resume mailbox setting not found"

[err-resume-mailbox-statistic-not-found]
other = "Resume mailbox statistic not found"

[err-invalid-credentials]
other = "Invalid mailbox credentials"

[err-mailbox-connection-failed]
other = "Mailbox connection failed"

[err-university-not-found]
other = "University not found"

[err-university-already-exists]
other = "University already exists"

[err-csv-file-not-found]
other = "CSV file not found"

[err-csv-parse-error]
other = "Failed to parse CSV file"

[err-csv-invalid-format]
other = "Invalid CSV file format"

[err-university-import-failed]
other = "Failed to import university data"
