[err-permission]
other = "无权操作"

[err-user-not-found]
other = "用户不存在"

[err-user-lock]
other = "用户已锁定"

[err-only-admin]
other = "仅管理员可操作"

[err-password]
other = "密码错误"

[err-invite-code-invalid]
other = "邀请码无效"

[err-email-invalid]
other = "邮箱格式错误"

[err-oauth-state-invalid]
other = "OAuth 状态无效"

[err-unsupported-platform]
other = "不支持的平台"

[err-not-invited]
other = "未被邀请"

[err-dingtalk-not-enabled]
other = "钉钉未启用"

[err-custom-not-enabled]
other = "OAuth未启用"

[err-user-limit]
other = "用户数量已达上限"

[err-miss-key]
other = "缺少文件名称"

[err-department-required]
other = "缺少部门ID"

[err-jobprofile-required]
other = "缺少岗位画像ID"

[err-jobskillmeta-required]
other = " 缺少技能ID"

[err-invalid-param]
other = "无效参数请检查: {{.message}}"

[err-jobprofile-has-resumes]
other = "岗位画像已关联简历"

[err-jobprofile-polish-min-length]
other = "岗位画像描述输入校验错误: {{.message}}"

[err-screening-task-not-found]
other = "筛选任务不存在"

[err-screening-task-running]
other = "正在进行中的任务不能删除，请等待任务完成或失败后再删除"

[err-screening-task-delete-failed]
other = "删除筛选任务失败"

[err-notification-setting-create-failed]
other = "创建通知设置失败: {{.message}}"

[err-notification-setting-get-failed]
other = "获取通知设置失败: {{.message}}"

[err-notification-setting-list-failed]
other = "获取通知设置列表失败: {{.message}}"

[err-notification-setting-update-failed]
other = "更新通知设置失败: {{.message}}"

[err-notification-setting-delete-failed]
other = "删除通知设置失败: {{.message}}"

[err-notification-setting-not-found]
other = "通知设置不存在: {{.message}}"

[err-resume-mailbox-setting-not-found]
other = "简历邮箱设置不存在"

[err-resume-mailbox-statistic-not-found]
other = "简历邮箱统计数据不存在"

[err-invalid-credentials]
other = "邮箱凭据无效"

[err-mailbox-connection-failed]
other = "邮箱连接失败"

[err-university-not-found]
other = "高校不存在"

[err-university-already-exists]
other = "高校已存在"

[err-csv-file-not-found]
other = "CSV文件不存在"

[err-csv-parse-error]
other = "CSV文件解析失败"

[err-csv-invalid-format]
other = "CSV文件格式无效"

[err-university-import-failed]
other = "高校数据导入失败"